import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"WFIF - Life Changing Radio 1500 AM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ic1.sslstream.com/wfif-fm",
            active: true,
        },
        {
            name:"WLOF - 101.7 FM The station of the Cross",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://hfc.streamguys1.com/wqom",
            active: false,
        },
        {
            name:"WRMB - Moody Radio South Florida 89.3 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://secondary.moodyradiostream.org/wrmb.mp3",
            active: false,
        },
        {
            name:"WBGL - Today's Christian Music 91.1 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://nwm.streamguys1.com/WBGL-MP3-4",
            active: false,
        },
        {
            name:"WJVK - Christian Family Radio 91.7 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice24.securenetsystems.net/WCVK",
            active: false,
        },
        {
            name:"WCRF-FM - Moody Radio 103.3 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://primary.moodyradiostream.org/wcrf.mp3",
            active: false,
        },
        {
            name:"KDJC - Christian Radio 88.1 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice7.securenetsystems.net/CSNAAC",
            active: false,
        },
        {
            name:"99.9 Live FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream2.cnmns.net/999livefm-mp3",
            active: false,
        },
        {
            name:"WMVW - New Life 91.7 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice6.securenetsystems.net/WMVV",
            active: false,
        },
        {
            name:"Power of Worship Radio",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://s4.radio.co/s325d5f1a1/listen",
            active: false,
        },
        {
            name:"Traditional Catholic Radio",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://traditionalcatholicradio.org:8000/main",
            active: false,
        },
        {
            name:"KLUX Good Company 89.5 FM live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://www.streamcontrol.net:8444/s/12340",
            active: false,
        },
        {
            name:"KCVV Radio Santísimo Sacramento 1240 AM live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://santissimo.stream.miriamtech.net:8000/kcvv",
            active: false,
        },
        {
            name:"WHIC The Station of the Cross - English live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://hfc.streamguys1.com/icatholicradio?_w=icatholicradio",
            active: false,
        },
        {
            name:"KHOY Catholic Radio 88.1 FM live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ic2.sslstream.com/khoy-fm?rnd=8762",
            active: false,
        },
        {
            name:"Radio Catholic live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ewtn-sgrewind.streamguys1.com/sgrewind/english/l_745_15156082_2526.aac",
            active: false,
        },
        {
            name:"Eastern Catholic Radio live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ais-edge37-live365-dal02.cdnstream.com/a79728",
            active: false,
        },
        {
            name:"WPBW-LP Relevant Radio 90.1 FM live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice42.securenetsystems.net/WPBW",
            active: false,
        },
        {
            name:"KJWM - Spirit Catholic Radio 91.5 FM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice7.securenetsystems.net/KVSS?",
            active: false,
        },
        {
            name:"KBVM Catholic Radio 88.3 FM live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://147.135.84.28/kbvm-fm",
            active: false,
        },
        {
            name:"RTVEmmaus English live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://server7.servistreaming.com/proxy/rtvemmauseng?mp=%2Fstream",
            active: false,
        },
        {
            name:"KJCR-LP EWTN Catholic Radio Network live",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ewtn-ice.streamguys1.com/english-aac",
            active: false,
        },
        {
            name:"Enain en Linea",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://cloudstream2032.conectarhosting.com/8310/stream",
            active: false,
        },
        {
            name:"ice7",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ice7.securenetsystems.net/KVSS",
            active: false,
        },
        {
            name:"WMET - Guadalupe Radio Network 1160 AM",
            artist: "Catholic Music",
            cover: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiMEHxXiVisvNvKrtusFe2OEvIC7i-8lC2dshhTnPheWzZDBoBWGJxT5mpkjrZB2VbbERC5TMSabrrfwW5D7cUj8eWfKZkCxUm5OpIubHM3GMMn8nrfebz2KsBvyAh2eqF3YSPMER7jqYyn7Fpmau0mcN84_W9kfBvTwu1_ifYAszgtccXxBQ1POSZbew/s320/dsd.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://grn-stream-01.miriamtech.net:8000/WMET1160AM.mp3",
            active: false,
        },
    ];
}

export default chillHop;

